barcode_index:
    path:     /
    defaults: { _controller: "TicketswapBarcodeBundle:Barcodes:index" }
    methods:  GET

barcode_show:
    path:     /{id}/show
    defaults: { _controller: "TicketswapBarcodeBundle:Barcodes:show" }
    methods:  GET

barcode_new:
    path:     /new
    defaults: { _controller: "TicketswapBarcodeBundle:Barcodes:new" }
    methods:  [GET, POST]

barcode_edit:
    path:     /{id}/edit
    defaults: { _controller: "TicketswapBarcodeBundle:Barcodes:edit" }
    methods:  [GET, POST]

barcode_delete:
    path:     /{id}/delete
    defaults: { _controller: "TicketswapBarcodeBundle:Barcodes:delete" }
    methods:  DELETE
