listing_show:
    path:     /{id}/show
    defaults: { _controller: "TicketswapListingBundle:Listings:show" }
    methods:  GET

listing_new:
    path:     /
    defaults: { _controller: "TicketswapListingBundle:Listings:newListingForm" }
    methods:  [GET]

listing_edit:
    path:     /{id}/edit
    defaults: { _controller: "TicketswapListingBundle:Listings:edit" }
    methods:  [GET, POST]

listing_delete:
    path:     /{id}/delete
    defaults: { _controller: "TicketswapListingBundle:Listings:delete" }
    methods:  DELETE
